    name: GitHub Classroom Workflow

    permissions:
      checks: write
      actions: read

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: education/autograding@v1
